config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'signup'  => 'users#new'

  post '/email_processor' => 'griddler/emails#create', as: :email_processor

  resources :outmails
  resources :inmails
  resources :users

  root 'outmails#home'

end

app/models/inmail.rb
class Inmail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/inmails_controller.rb
class InmailsController < ApplicationController

  before_action :set_inmail, only: [:show, :edit, :update, :destroy]



  def index
    @inmails = Inmail.all
    @current_user = User.find_by(id: session[:user_id])

  end

  def destroy
    @inmail.destroy
    respond_to do |format|
      format.html { redirect_to inmails_path, notice: 'Inmail was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def update

  end

  def show

  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_inmail
    @inmail = Inmail.find(params[:id])
  end



  # Never trust parameters from the scary internet, only allow the white list through.
  def inmail_params
    params.require(:inmail).permit(:to, :subject, :body)
  end
end

app/helpers/inmails_helper.rb
module InmailsHelper

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/views/inmails/_form.html.erb
<%= form_for(@inmail) do |f| %>
  <% if @inmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inmail.errors.count, "error") %> prohibited this inmail from being saved:</h2>

      <ul>
      <% @inmail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :headers %><br>
    <%= f.text_field :headers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inmails/edit.html.erb
<h1>Editing Inmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @inmail %> |
<%= link_to 'Back', inmails_path %>

app/views/inmails/index.html.erb
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="col-md-2">
          <%= button_to "New Email", new_outmail_path, :method => :get %>

        </div>

        <div class="col-md-2">
       <%= button_to "logout", logout_path, :method => :delete %>

        </div>

        <div class="col-md-1">
          <p></p>
        </div>




        <div class="col-md-8">
          <% if @inmails.count > 0 %>


        <h1>Inbox</h1>

          <table class ='table table-responsive table-striped table-hover table-condensed'>
            <thead>






                <tr>

                  <th>&nbsp &nbsp From</th>
                  <th>Message</th>
                  <th>Date</th>
                  <th colspan="3"></th>
                </tr>
                </thead>

                <tbody>
                <% @inmails.each do |inmail| %>

                    <% if inmail.to.to_s.include?(@current_user.zmail) %>
                    <tr>

                      <td><%= inmail.to %></td>

                      <td><%= inmail.from %></td>
                      <td><%= inmail.body %></td>
                      <td><%= link_to 'Show', inmail %></td>
                      <td><%= link_to 'Destroy', inmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>

                    </tr>
                    <% end %>

                <% end %>
                </tbody>


                     <% else %>
                       <p><em>your mailbox is empty</em></p>
                      <% end %>


            </table>

        </div>
        <!--Body content-->
      </div>
    </div>

app/views/inmails/new.html.erb
<h1>New Inmail</h1>

<%= render 'form' %>

<%= link_to 'Back', inmails_path %>

app/views/inmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @inmail.to %>
</p>

<p>
  <strong>From:</strong>
  <%= @inmail.from %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @inmail.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @inmail.body %>
</p>

<p>
  <strong>Headers:</strong>
  <%= @inmail.headers %>
</p>

<%= link_to 'Edit', edit_inmail_path(@inmail) %> |
<%= link_to 'Back', inmails_path %>