config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'signup'  => 'users#new'

  post '/email_processor' => 'griddler/emails#create', as: :email_processor

  resources :outmails
  resources :inmails
  resources :users

  root 'outmails#home'

end

app/models/outmail.rb
class Outmail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/outmails_controller.rb
class OutmailsController < ApplicationController
  before_action :set_outmail, only: [:show, :edit, :update, :destroy]

  def home

  end


  # GET /outmails
  # GET /outmails.json
  def index
    @outmails = Outmail.all
  end

  # GET /outmails/1
  # GET /outmails/1.json
  def show
  end

  # GET /outmails/new
  def new
    @outmail = Outmail.new
  end

  # GET /outmails/1/edit
  def edit
  end

  # POST /outmails
  # POST /outmails.json
  def create
    @outmail = Outmail.new(outmail_params)

    respond_to do |format|
      if @outmail.save
        Emailer.deliver_email(@outmail).deliver_now
        format.html { redirect_to inmails_path, notice: 'Outmail was successfully created.' }
        format.json { render :show, status: :created, location: @inmail }
      else
        format.html { render :new }
        format.json { render json: @outmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outmails/1
  # PATCH/PUT /outmails/1.json
  def update
    respond_to do |format|
      if @outmail.update(outmail_params)
        format.html { redirect_to @outmail, notice: 'Outmail was successfully updated.' }
        format.json { render :show, status: :ok, location: @outmail }
      else
        format.html { render :edit }
        format.json { render json: @outmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outmails/1
  # DELETE /outmails/1.json
  def destroy
    @outmail.destroy
    respond_to do |format|
      format.html { redirect_to outmails_url, notice: 'Outmail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outmail
      @outmail = Outmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outmail_params
      params.require(:outmail).permit(:to, :subject, :body)
    end
end

app/helpers/outmails_helper.rb
module OutmailsHelper
end

app/views/outmails/_form.html.erb
<%= form_for(@outmail) do |f| %>
  <% if @outmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outmail.errors.count, "error") %> prohibited this outmail from being saved:</h2>

      <ul>
      <% @outmail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outmails/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '#' %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/outmails/edit.html.erb
<h1>Editing Outmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @outmail %> |
<%= link_to 'Back', outmails_path %>

app/views/outmails/home.html.erb
<!--
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">


    <nav>

      <%= link_to "zəʊməʊ", '#', id: "logo" %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
       </ul>

    </nav>

  </div>
</header>

<div class="jumbotron">
  <div class="container">
    <h1>zhomos.com</h1>
    <p>carry your email to the mountaintop...</p>
  </div>


</div>


-->






























<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Scrolling Nav - Start Bootstrap Template</title>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/scrolling-nav.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">




<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>







      <a class="navbar-brand page-scroll" href="#page-top"><a id="logo">zəʊməʊ</a></a>    <!-- this is the logo and id -->
    </div>                                                                                <!-- very important -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">




      <ul class="nav navbar-nav navbar-right">   <!-- very very vvery important, add navbar-right at the end -->






        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a class="page-scroll" href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#about">Sign Up</a>
        </li>
        <li>
          <a class="page-scroll" href="#services">Login</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<!-- Intro Section -->
<section id="intro" class="intro-section">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p></p>
          <br>
          <p></p>
          <br>
          <p></p>


          <h1>zhomos.com</h1>
          <p>carry your email to the mountaintop</p>
          <!-- <a class="btn btn-default page-scroll" href="#about">Click Me to Scroll Down!</a> -->
        </div>
      </div>
    </div>
  </div>
</section>

<section id="about" class="about-section">
  <div class="signup">                  <!-- this is the class that you use in your custom.css file to change the background -->
  <div class="container">
    <div class="row">
      <div align="center"><div class="col-lg-12">
        <button type="button" class="btn btn-primary btn-lg btn-block"><%= button_to "Sign up now!", signup_path, :method => :get %></button>
      </div>
      </div>
    </div>
  </div>
  </div>
</section>

<!-- Services Section -->
<section id="services" class="services-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1><%= link_to 'Login', login_path %></h1>
      </div>
    </div>
  </div>
</section>

<!-- Contact Section -->
<section id="contact" class="contact-section">
  <div class="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Contact Section</h1>
      </div>
    </div>
  </div>
      </div>
</section>

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Scrolling Nav JavaScript -->
<script src="js/jquery.easing.min.js"></script>
<script src="js/scrolling-nav.js"></script>




</body>

</html>

app/views/outmails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Outmails</h1>

<table>
  <thead>
    <tr>
      <th>To</th>
      <th>Subject</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outmails.each do |outmail| %>
      <tr>
        <td><%= outmail.to %></td>
        <td><%= outmail.subject %></td>
        <td><%= outmail.body %></td>
        <td><%= link_to 'Show', outmail %></td>
        <td><%= link_to 'Edit', edit_outmail_path(outmail) %></td>
        <td><%= link_to 'Destroy', outmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outmail', new_outmail_path %>

app/views/outmails/new.html.erb
<h1>New Outmail</h1>


<%= render 'form' %>

<%= link_to 'Back', outmails_path %>

app/views/outmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @outmail.to %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @outmail.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @outmail.body %>
</p>

<%= link_to 'Edit', edit_outmail_path(@outmail) %> |
<%= link_to 'Back', outmails_path %>